#+title: 第 1 章 手続きによる抽象

- [[http://community.schemewiki.org/?sicp-solutions][sicp-solutions]]
- https://github.com/bixuanzju/sicp-exercises-elisp

* 1.1
  Below is a sequence of expressions.  What is the
  result printed by the interpreter in response to each expression?
  Assume that the sequence is to be evaluated in the order in which
  it is presented.

#+begin_src emacs-lisp
10					; => 

(+ 5 3 4)				; => 

(- 9 1)					; => 

(/ 6 2) 				; => 

(+ (* 2 4) (- 4 6))			; => 

(setq a 3)				; => 

(setq b (+ a 1))			; => 

(+ a b (* a b))				; => 

(= a b)					; => 

(if (and (> b a) (< b (* a b)))
    b
  a)					; => 

(cond ((= a 4) 6)
      ((= b 4) (+ 6 7 a))
      (t 25))				; => 

(+ 2 (if (> b a) b a))			; => 

(* (cond ((> a b) a)
	 ((< a b) b)
	 (t -1))
   (+ a 1))				; => 
#+end_src

* 1.2

#+begin_src emacs-lisp
(/ (+ 5 4 (- 2 (- 3 (+ 6 (/ 4.0 5))))) (* 3 (- 6 2) (- 2 7)))
#+end_src

* 1.3
  3 つの数値を引数として取り, 内 2 つの大きな数値
  の二乗の和を返す手続を定義せよ.

#+begin_src emacs-lisp
(defun ex1-3 (a b c)
  (cond ((and (< a b) (< a c))
	(+ (* b b) (* c c)))
	((and (< b a) (< b c))
	(+ (* a a) (* c c)))
	(t
	 (+ (* a a) (* b b)))))
#+end_src

* 1.4:
  我々の評価モデルがオペレータが複合式である組み
  合わせを可能にすることを観察せよ. この観察結果を用いて次の
  手続の挙動を説明せよ:
  
#+begin_src emacs-lisp
(defun a-plus-abs-b (a b)
  (if (> b 0)
       (+ a b)
    (- a b)))

(a-plus-abs-b 1 1)
(a-plus-abs-b 1 -1)
#+end_src

* 1.5:
  Ben Bitdiddle は自分が直面するインタプリタが適用順評価と
  正規順評価のどちらを用いるか決定するテストを開発した.

  まず以下の 2 つの手続を定義する.次に以下の式を評価する.

#+begin_src emacs-lisp
(defun p () p)

(defun test (acc y)
  (if (= acc 0) 0 y))

(test 0 'p)
#+end_src

Ben は適用順評価を用いるインタプリタではどのような挙動を観察するだろうか? 
Ben は正規順評価を用いるインタプリタではどのような挙動を観察するだろうか? 

あなたの回答を説明せよ. 

(特殊形式の if はインタプリタが適用順評価でも正規順評価でも同じ
挙動を行うと仮定せよ:
述語式が最初に評価され, 
結果が consequent と alternative のどちらを評価するか決定する)

* 1.6

#+begin_src emacs-lisp
(defun new-if (predicate then-clause else-clause)
  (cond (predicate then-clause)
	(t else-clause)))

(new-if (= 2 3) 0 5)
(new-if (= 1 1) 0 5)

(defun squr-iter (guess acc)
  (new-if (good-enough? guess acc)
      guess
    (squr-iter (improve guess acc)
	       acc)))

(defun improve (guess acc)
  (average guess (/ acc guess)))

(defun average (acc y)
  (/ (+ acc y) 2))

(defun square (guess)
  (expt guess 2))

(defun good-enough? (guess acc)
  (< (abs (- (square guess) acc)) 0.001))

(defun my-sqrt (acc)
  (squr-iter 1.0 acc))
  
(my-sqrt 9)
#+end_src

-> max-lisp-eval-depth
  http://community.schemewiki.org/?sicp-ex-1.6

* 1.7

(my-sqrt 900000000000000000000000000000)
-> max-lisp-eval-depth

(my-sqrt 0.00000000000000000000000000001)
-> 0.3125 のまま.

#+begin_src emacs-lisp
(defun squr-iter (guess pre-guess acc)
  (if (good-enough? guess pre-guess)
      guess
    (squr-iter (improve guess acc) guess
	       acc)))

(defun improve (guess acc)
  (average guess (/ acc guess)))

(defun average (acc y)
  (/ (+ acc y) 2))

(defun square (guess)
  (expt guess 2))

(defun good-enough? (guess pre-guess)
  (< (abs (- guess pre-guess)) 0.001))

(defun my-sqrt (acc)
  (squr-iter 1.0 2.0 acc))

(my-sqrt 9)

#+end_src

- http://community.schemewiki.org/?sicp-ex-1.7

* 1.8
  Newton's method for cube roots is based on the
  fact that if y is an approximation to the cube root of acc, then a
  better approximation is given by the value
  
  x/y^2 + 2y
  ----------
      3
  
  Use this formula to implement a cube-root procedure analogous to
  the square-root procedure.  (In section *Note 1-3-4:: we will see
  how to implement Newton's method in general as an abstraction of
  these square-root and cube-root procedures.)

#+begin_src emacs-lisp
(defun cube-iter (guess acc)
  (if (good-enough? guess acc)
      guess
    (cube-iter (improve guess acc)
	       acc)))

(defun improve (guess acc)
  (/ (+ (/ acc (expt guess 2)) (* 2 guess)) 3))

(defun good-enough? (guess acc)
  (< (abs (- (cube guess) acc)) 0.001))

(defun cube (guess)
  (expt guess 3))

(defun my-cube (acc)
    (cube-iter 1.0 acc))

(my-cube 27)
#+end_src

* 1.9
  lecture と同じなので, 省略.

  Iterative な定義.

 #+begin_src emacs-lisp
;; normal-order evaluation
;; linier iteration
(defun plus (acc y)
  (if (= acc 0)
      y
    (+ (1- acc) (1+ y))))
#+end_src

   Recursive な定義.

#+begin_src emacs-lisp
;; applicative-order evaluation
;; linier recursion
(defun plus (acc y)
  (if (= acc 0)
      y
    (1+ (+ (1- acc) y))))
(plus 4 5)
#+end_src

* 1.10
  The following procedure computes a mathematical
  function called Ackermann's function.

#+begin_src emacs-lisp
(defun A (acc y)
  (cond ((= y 0) 0)
	((= acc 0) (* 2 y))
	((= y 1) 2)
	(t (A (- acc 1)
		 (A acc (- y 1))))))
#+end_src

What are the values of the following expressions?

#+begin_src emacs-lisp
(A 1 10)				; => 

(A 2 4)					; => 

(A 3 3)					; => 
#+end_src

Consider the following procedures, where `A' is the procedure

#+begin_src emacs-lisp
(defun k (n) (* 5 n n))
;; 5n^2
(k 2)					; => 

;; ------------------
(defun f (n) (A 0 n))
;; 2n
(f 1)					; => 
(f 2)					; => 
(f 4)					; => 

;; ------------------
(defun g (n) (A 1 n))
;; 2^n
(g 1)					; => 
(g 2)					; => 
(g 3)					; => 
(g 4)					; => 

;; ------------------
;; 2^2^2^2^...(n times)
(defun h (n) (A 2 n))
(h 1)					; => 
(A 2 1)					; => 

(h 2)					; => 
(h 3)					; => 
(h 4)					; => 
;; (h 5)				; => error.

#+end_src

Give concise mathematical definitions for the functions computed
by the procedures `f', `g', and `h' for positive integer values of
n.  For example, `(k n)' computes 5n^2.

- http://community.schemewiki.org/?sicp-ex-1.10

* 1.11:
  A function f is defined by the rule that
  - f (n) = n , if n<3 
  - f (n) = f (n - 1) + 2f (n - 2) + 3f (n - 3) , if n>= 3. 

  - http://community.schemewiki.org/?sicp-ex-1.11

** recursive process 
  Write a procedure that computes f by means of a recursive process.

#+begin_src emacs-lisp
(defun f (n)
  (if (< n 3)
      n
      (+ (f (- n 1))
	 (* 2 (f (- n 2)))
	 (* 3 (f (- n 3))))))

(f 2)				; => 
(f 3)				; => 
(f 5)				; => 
#+end_src

** iterative
  Write a procedure that computes f 
  by means of an iterative process.

  #+begin_src emacs-lisp
(defun f (n)
  (defun fn-iter (count n f1 f2 f3) 
    (if (= count n)
	f3
	(fn-iter (+ count 1) n f2 f3 (+ (* 3 f1) (* 2 f2) f3))))
  
  (if (< n 3)
      n
      (fn-iter 2 n 0 1 2)))

(f 1)
(f 3)
(f 4)
(f 5)
#+end_src

* 1.12
  The following pattern of numbers is called "Pascal's triangle".

#+begin_src text
                  1
                1   1
              1   2   1
            1   3   3   1
          1   4   6   4   1
#+end_src

  The numbers at the edge of the triangle are all 1, and each number
  inside the triangle is the sum of the two numbers above it.(4)
  Write a procedure that computes elements of Pascal's triangle by
  means of a recursive process.

#+begin_src emacs-lisp
(defun pascal (row col)
  (cond ((eq col 1)
	 1)
	((eq row 1)
	 1)
	(t
	 (+ (pascal (1- row) col) (pascal row (1- col))))))
  
(pascal 1 1)
(pascal 2 1)				; => 
(pascal 1 2)				; => 
(pascal 2 2)				; => 
(pascal 2 3)				; => 
(pascal 3 3)				; => 
#+end_src

* 1.13
  Prove that _Fib_(n) is the closest integer to
  [phi]^n/[sqrt] (5), where [phi] = (1 + [sqrt] (5))/2.  Hint: Let
  [illegiblesymbol] = (1 - [sqrt] (5))/2.  Use induction and the
  definition of the Fibonacci numbers (see section *Note 1-2-2::) to
  prove that _Fib_(n) = ([phi]^n - [illegiblesymbol]^n)/[sqrt] (5).

  skip :)
  
* 1.14,15 
  skip :)

* 1.16

#+begin_src emacs-lisp
(defun fast-expt (b n) 
  (defun iter (a b n)
    (if (= n 0)
	a
	(if (even n)
	    (iter a (square b) (/ n 2))
	    (iter (* a b) b (- n 1)))))
  (iter 1 b n))

(defun even (n) (= (% n 2) 0))
(defun square (acc) (* acc acc))

(even 2)
(even 3)

(fast-expt 2 0)
(fast-expt 2 1) 
(fast-expt 2 2)
(fast-expt 2 4) 
(fast-expt 2 8) 
(fast-expt 2 16)
#+end_src

* 1.17

#+begin_src emacs-lisp
(defun * (a b)
  (if (= b 0)
      0
      (+ a (* a (- b 1)))))

(* 1 0)
(* 1 1)
(* 2 2)
#+end_src

#+begin_src emacs-lisp
(defun * (a b)
  (defun iter (a b acc)
    (if (= b 0)
	acc
	(iter a (1- b) (+ a acc))))
  (iter a b 0))

(* 1 0)
(* 1 1)
(* 2 2)
(* 2 3)
#+end_src

* 1.18

#+begin_src emacs-lisp
(defun even (n) (= (% n 2) 0))
(defun square (acc) (* acc acc))

(defun * (a b)
  (defun iter (acc a b)
    (cond ((= b 0) acc)
	  ((even b) (iter acc (square a) (/ b 2)))
	  (t (iter (+ acc a) a (- b 1)))))
  (iter a b 0))

(* 2 4)
(* 4 0)
#+end_src

* 1.19
  pass...
* 1.21

#+begin_src emacs-lisp
(defun smallest-divisor (n)
  (find-divisor n 2))

(defun find-divisor (n test-divisor)
  (cond ((> (square test-divisor) n) n)
	((divides? test-divisor n) test-divisor)
	(t (find-divisor n (+ test-divisor 1)))))

(defun divides? (a b)
  (= (% b a) 0))

(defun square (x) (* x x))

(defun prime? (n)
  (= n (smallest-divisor n)))

(prime? 199)				; => 
(prime? 1999)				; => 
(prime? 19999)				; => 
#+end_src

* 1.22

#+begin_src emacs-lisp
(defun timed-prime-test (n)
  (print "\n")
  (print n)
  (start-prime-test n (get-runtime)))

(defun start-prime-test (n start-time)
  (if (prime? n)
      (report-prime (- (get-runtime) start-time))))

(defun report-prime (elapsed-time)
  (print " *** ")
  (print elapsed-time))

(defun get-runtime ()
  (+ (* (nth 1 (get-internal-run-time)) 1000)
     (nth 2 (get-internal-run-time))))

(timed-prime-test 199)			; => 

;; elisp では, スタックオーバーフローが発生してしまう.
;; (timed-prime-test 1000000007)
#+end_src

* 1.23
  2 の倍数はスキップするように改良.

#+begin_src emacs-lisp
(defun smallest-divisor (n)
  (find-divisor n 2))

(defun find-divisor (n test-divisor)
  (cond ((> (square test-divisor) n) n)
	((divides? test-divisor n) test-divisor)
	(t (find-divisor n (next test-divisor)))))

(defun divides? (a b)
  (= (% b a) 0))

(defun square (x) (* x x))

(defun next (n)
  (cond ((= n 2) 3)
	(t
	 (+ n 2))))

(defun prime? (n)
  (= n (smallest-divisor n)))

(next 2)
(next 3)
(next 5)

(prime? 199)				; => 
(prime? 1999)				; => 
#+end_src

* 1.24
  elisp ではできないのでバス.

* 1.25-28
  skip :)

* 1.29

#+begin_src emacs-lisp
(defun even? (a) (= (% a 2) 0))
(defun inc (n) (+ n 1))
(defun cube (n) (* n n n))

(defun sum (term a next b)
  (if (> a b) 0
      (+ (funcall term a)
	 (sum term (funcall next a) next b))))

(defun simpson (f aa bb n)
  (let* ((h (/ (- bb aa) (float n)))
	 (yk (lambda (k) (funcall f (+ aa (* h k)))))
         (simpson-term (lambda (k)
			 (* (cond ((or (= k 0) (= k n)) 1)
				  ((even? k) 2)
				  (t 4))
			    (funcall yk k)))))
    (* (/ h 3) (sum simpson-term aa 'inc n))))

(simpson 'cube 0 1 2)			; => 0.25
(simpson 'cube 0 1 100)			; => 0.24999999999999992
;;(simpson 'cube 0 1 1000)		; => 
#+end_src

* 1.30
  反復的プロセスへの書き換え.

#+begin_src emacs-lisp
(defun inc (n) (+ n 1))
(defun cube (x) (* x x x))

(defun sum-cubes (a b)
  (sum 'cube a 'inc b))

(defun sum (f sum-a next sum-b)
  (defun iter (iter-a result)
    (if (> iter-a sum-b)
	result
	(iter (funcall next iter-a) (+ result (funcall f iter-a)))))
  (iter sum-a 0))

(sum-cubes 1 10)			; => 3025
#+end_src

* 1.31
